-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Beatmon.Api.Object.AccountsConnection exposing (edges, nodes, pageInfo, selection, totalCount)

import Beatmon.Api.InputObject
import Beatmon.Api.Interface
import Beatmon.Api.Object
import Beatmon.Api.Scalar
import Beatmon.Api.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Beatmon.Api.Object.AccountsConnection
selection constructor =
    Object.selection constructor


{-| A list of `Account` objects.
-}
nodes : SelectionSet decodesTo Beatmon.Api.Object.Account -> Field (List (Maybe decodesTo)) Beatmon.Api.Object.AccountsConnection
nodes object_ =
    Object.selectionField "nodes" [] object_ (identity >> Decode.nullable >> Decode.list)


{-| A list of edges which contains the `Account` and cursor to aid in pagination.
-}
edges : SelectionSet decodesTo Beatmon.Api.Object.AccountsEdge -> Field (List decodesTo) Beatmon.Api.Object.AccountsConnection
edges object_ =
    Object.selectionField "edges" [] object_ (identity >> Decode.list)


{-| Information to aid in pagination.
-}
pageInfo : SelectionSet decodesTo Beatmon.Api.Object.PageInfo -> Field decodesTo Beatmon.Api.Object.AccountsConnection
pageInfo object_ =
    Object.selectionField "pageInfo" [] object_ identity


{-| The count of _all_ `Account` you could get from the connection.
-}
totalCount : Field (Maybe Int) Beatmon.Api.Object.AccountsConnection
totalCount =
    Object.fieldDecoder "totalCount" [] (Decode.int |> Decode.nullable)
