-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Beatmon.Api.Object.HeartbeatLog exposing (accountId, date, heartbeatByHeartbeatIdAndAccountId, heartbeatId, nodeId, selection)

import Beatmon.Api.InputObject
import Beatmon.Api.Interface
import Beatmon.Api.Object
import Beatmon.Api.Scalar
import Beatmon.Api.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Beatmon.Api.Object.HeartbeatLog
selection constructor =
    Object.selection constructor


{-| A globally unique identifier. Can be used in various places throughout the system to identify this single value.
-}
nodeId : Field Beatmon.Api.Scalar.Id Beatmon.Api.Object.HeartbeatLog
nodeId =
    Object.fieldDecoder "nodeId" [] (Object.scalarDecoder |> Decode.map Beatmon.Api.Scalar.Id)


date : Field Beatmon.Api.Scalar.Datetime Beatmon.Api.Object.HeartbeatLog
date =
    Object.fieldDecoder "date" [] (Object.scalarDecoder |> Decode.map Beatmon.Api.Scalar.Datetime)


heartbeatId : Field Beatmon.Api.Scalar.Uuid Beatmon.Api.Object.HeartbeatLog
heartbeatId =
    Object.fieldDecoder "heartbeatId" [] (Object.scalarDecoder |> Decode.map Beatmon.Api.Scalar.Uuid)


accountId : Field Beatmon.Api.Scalar.BigInt Beatmon.Api.Object.HeartbeatLog
accountId =
    Object.fieldDecoder "accountId" [] (Object.scalarDecoder |> Decode.map Beatmon.Api.Scalar.BigInt)


{-| Reads a single `Heartbeat` that is related to this `HeartbeatLog`.
-}
heartbeatByHeartbeatIdAndAccountId : SelectionSet decodesTo Beatmon.Api.Object.Heartbeat -> Field (Maybe decodesTo) Beatmon.Api.Object.HeartbeatLog
heartbeatByHeartbeatIdAndAccountId object_ =
    Object.selectionField "heartbeatByHeartbeatIdAndAccountId" [] object_ (identity >> Decode.nullable)
