-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Beatmon.Api.Object exposing (Account(..), AccountsConnection(..), AccountsEdge(..), AuthenticatePayload(..), CreateAccountPayload(..), CreateHeartbeatLogPayload(..), CreateHeartbeatPayload(..), DeleteAccountPayload(..), DeleteHeartbeatLogPayload(..), DeleteHeartbeatPayload(..), Heartbeat(..), HeartbeatLog(..), HeartbeatLogsConnection(..), HeartbeatLogsEdge(..), HeartbeatsConnection(..), HeartbeatsEdge(..), PageInfo(..), RefreshTokenPayload(..), UpdateAccountPayload(..), UpdateHeartbeatLogPayload(..), UpdateHeartbeatPayload(..))


type Account
    = Account


type AccountsConnection
    = AccountsConnection


type AccountsEdge
    = AccountsEdge


type AuthenticatePayload
    = AuthenticatePayload


type CreateAccountPayload
    = CreateAccountPayload


type CreateHeartbeatLogPayload
    = CreateHeartbeatLogPayload


type CreateHeartbeatPayload
    = CreateHeartbeatPayload


type DeleteAccountPayload
    = DeleteAccountPayload


type DeleteHeartbeatLogPayload
    = DeleteHeartbeatLogPayload


type DeleteHeartbeatPayload
    = DeleteHeartbeatPayload


type Heartbeat
    = Heartbeat


type HeartbeatLog
    = HeartbeatLog


type HeartbeatLogsConnection
    = HeartbeatLogsConnection


type HeartbeatLogsEdge
    = HeartbeatLogsEdge


type HeartbeatsConnection
    = HeartbeatsConnection


type HeartbeatsEdge
    = HeartbeatsEdge


type PageInfo
    = PageInfo


type RefreshTokenPayload
    = RefreshTokenPayload


type UpdateAccountPayload
    = UpdateAccountPayload


type UpdateHeartbeatLogPayload
    = UpdateHeartbeatLogPayload


type UpdateHeartbeatPayload
    = UpdateHeartbeatPayload
