-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Beatmon.Api.Scalar exposing (BigInt(..), Cursor(..), Datetime(..), Id(..), JwtToken(..), Uuid(..))


type BigInt
    = BigInt String


type Cursor
    = Cursor String


type Datetime
    = Datetime String


type Id
    = Id String


type JwtToken
    = JwtToken String


type Uuid
    = Uuid String
