-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Beatmon.Api.Enum.AccountsOrderBy exposing (AccountsOrderBy(..), decoder, toString)

import Json.Decode as Decode exposing (Decoder)


{-| Methods to use when ordering `Account`.
-}
type AccountsOrderBy
    = Natural
    | AccountIdAsc
    | AccountIdDesc
    | EmailAsc
    | EmailDesc
    | IsAdminAsc
    | IsAdminDesc
    | IsActiveAsc
    | IsActiveDesc
    | PrimaryKeyAsc
    | PrimaryKeyDesc


decoder : Decoder AccountsOrderBy
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "NATURAL" ->
                        Decode.succeed Natural

                    "ACCOUNT_ID_ASC" ->
                        Decode.succeed AccountIdAsc

                    "ACCOUNT_ID_DESC" ->
                        Decode.succeed AccountIdDesc

                    "EMAIL_ASC" ->
                        Decode.succeed EmailAsc

                    "EMAIL_DESC" ->
                        Decode.succeed EmailDesc

                    "IS_ADMIN_ASC" ->
                        Decode.succeed IsAdminAsc

                    "IS_ADMIN_DESC" ->
                        Decode.succeed IsAdminDesc

                    "IS_ACTIVE_ASC" ->
                        Decode.succeed IsActiveAsc

                    "IS_ACTIVE_DESC" ->
                        Decode.succeed IsActiveDesc

                    "PRIMARY_KEY_ASC" ->
                        Decode.succeed PrimaryKeyAsc

                    "PRIMARY_KEY_DESC" ->
                        Decode.succeed PrimaryKeyDesc

                    _ ->
                        Decode.fail ("Invalid AccountsOrderBy type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : AccountsOrderBy -> String
toString enum =
    case enum of
        Natural ->
            "NATURAL"

        AccountIdAsc ->
            "ACCOUNT_ID_ASC"

        AccountIdDesc ->
            "ACCOUNT_ID_DESC"

        EmailAsc ->
            "EMAIL_ASC"

        EmailDesc ->
            "EMAIL_DESC"

        IsAdminAsc ->
            "IS_ADMIN_ASC"

        IsAdminDesc ->
            "IS_ADMIN_DESC"

        IsActiveAsc ->
            "IS_ACTIVE_ASC"

        IsActiveDesc ->
            "IS_ACTIVE_DESC"

        PrimaryKeyAsc ->
            "PRIMARY_KEY_ASC"

        PrimaryKeyDesc ->
            "PRIMARY_KEY_DESC"
