-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Beatmon.Api.Enum.HeartbeatsOrderBy exposing (HeartbeatsOrderBy(..), decoder, toString)

import Json.Decode as Decode exposing (Decoder)


{-| Methods to use when ordering `Heartbeat`.
-}
type HeartbeatsOrderBy
    = Natural
    | HeartbeatIdAsc
    | HeartbeatIdDesc
    | AccountIdAsc
    | AccountIdDesc
    | NameAsc
    | NameDesc
    | NotifyAfterSecondsAsc
    | NotifyAfterSecondsDesc
    | PrimaryKeyAsc
    | PrimaryKeyDesc


decoder : Decoder HeartbeatsOrderBy
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "NATURAL" ->
                        Decode.succeed Natural

                    "HEARTBEAT_ID_ASC" ->
                        Decode.succeed HeartbeatIdAsc

                    "HEARTBEAT_ID_DESC" ->
                        Decode.succeed HeartbeatIdDesc

                    "ACCOUNT_ID_ASC" ->
                        Decode.succeed AccountIdAsc

                    "ACCOUNT_ID_DESC" ->
                        Decode.succeed AccountIdDesc

                    "NAME_ASC" ->
                        Decode.succeed NameAsc

                    "NAME_DESC" ->
                        Decode.succeed NameDesc

                    "NOTIFY_AFTER_SECONDS_ASC" ->
                        Decode.succeed NotifyAfterSecondsAsc

                    "NOTIFY_AFTER_SECONDS_DESC" ->
                        Decode.succeed NotifyAfterSecondsDesc

                    "PRIMARY_KEY_ASC" ->
                        Decode.succeed PrimaryKeyAsc

                    "PRIMARY_KEY_DESC" ->
                        Decode.succeed PrimaryKeyDesc

                    _ ->
                        Decode.fail ("Invalid HeartbeatsOrderBy type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : HeartbeatsOrderBy -> String
toString enum =
    case enum of
        Natural ->
            "NATURAL"

        HeartbeatIdAsc ->
            "HEARTBEAT_ID_ASC"

        HeartbeatIdDesc ->
            "HEARTBEAT_ID_DESC"

        AccountIdAsc ->
            "ACCOUNT_ID_ASC"

        AccountIdDesc ->
            "ACCOUNT_ID_DESC"

        NameAsc ->
            "NAME_ASC"

        NameDesc ->
            "NAME_DESC"

        NotifyAfterSecondsAsc ->
            "NOTIFY_AFTER_SECONDS_ASC"

        NotifyAfterSecondsDesc ->
            "NOTIFY_AFTER_SECONDS_DESC"

        PrimaryKeyAsc ->
            "PRIMARY_KEY_ASC"

        PrimaryKeyDesc ->
            "PRIMARY_KEY_DESC"
